//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AVFoundation/AVFoundation.h>
#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <CoreMedia/CoreMedia.h>

@interface LTPlayerDisplayView : UIView

@property(retain, nonatomic) AVPlayer *player;

@end



@interface LTPlayControlView : UIView

@end


@interface LTPlayControlFSAdBottomView : UIView

@end


@interface LTPlayControlFSAdTopView : UIView

@end






@interface LTMoviePlayerViewController : UIViewController


@property(nonatomic) double lastRecordSecond;
- (double)adCurrentTime;

@property(retain, nonatomic) LTPlayControlView *viewPlayControl; // @synthesize viewPlayControl=_viewPlayControl;


@property(retain, nonatomic) LTPlayControlFSAdBottomView *viewAdBottomPlayControl; // @synthesize viewAdBottomPlayControl=_viewAdBottomPlayControl;
@property(retain, nonatomic) LTPlayControlFSAdTopView *viewAdTopPlayControl; // @synthesize viewAdTopPlayControl=_viewAdTopPlayControl;

@end



