//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HHTimer, NSMutableArray, NSObject<OS_dispatch_queue>, SpeedUpTrialModel;

@interface FileTransSpeedUpTrialManager : NSObject
{
    long long _probationaryStatus;
    HHTimer *_probationaryTimer;
    long long _probationaryDuration;
    long long _probationaryTag;
    SpeedUpTrialModel *_probationaryModel;
    NSMutableArray *_beforeProbationSpeedArray;
    NSMutableArray *_probationSpeedArray;
    double _probationaryIncrease;
    double _preTime;
    double _timestamp;
    NSObject<OS_dispatch_queue> *_speedCalculateQueue;
}

+ (void)destroyInstance;
+ (id)new;
+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *speedCalculateQueue; // @synthesize speedCalculateQueue=_speedCalculateQueue;
@property(nonatomic) double timestamp; // @synthesize timestamp=_timestamp;
@property(nonatomic) double preTime; // @synthesize preTime=_preTime;
@property(nonatomic) double probationaryIncrease; // @synthesize probationaryIncrease=_probationaryIncrease;
@property(retain, nonatomic) NSMutableArray *probationSpeedArray; // @synthesize probationSpeedArray=_probationSpeedArray;
@property(retain, nonatomic) NSMutableArray *beforeProbationSpeedArray; // @synthesize beforeProbationSpeedArray=_beforeProbationSpeedArray;
@property(retain, nonatomic) SpeedUpTrialModel *probationaryModel; // @synthesize probationaryModel=_probationaryModel;
@property long long probationaryTag; // @synthesize probationaryTag=_probationaryTag;
@property(nonatomic) long long probationaryDuration; // @synthesize probationaryDuration=_probationaryDuration;
@property(retain, nonatomic) HHTimer *probationaryTimer; // @synthesize probationaryTimer=_probationaryTimer;
@property long long probationaryStatus; // @synthesize probationaryStatus=_probationaryStatus;
- (void).cxx_destruct;
- (id)getProbationSubmitTitle;
- (id)getProbationTitleWithIncrease:(double)arg1;
- (id)getProbationJumpUrl:(long long)arg1;
- (long long)probationDuration;
- (void)checkProbationary;
- (void)setupTimer;
- (void)stopTimer;
- (void)handleProbationaryTimer;
- (void)calculateProbationIncrease;
- (long long)calculateAverageSpeed:(id)arg1;
- (id)trialToken;
- (long long)trialTimeStamp;
- (void)downloadTaskNone;
- (void)notifyProbationChange;
- (void)resetTrialStatus;
- (void)cancelTrialImmediately:(BOOL)arg1;
- (void)stopProbationTask;
- (void)startTrial;
- (void)handleVipInfoChanged:(id)arg1;
- (void)handleLogout:(id)arg1;
- (void)handleProgressChanged:(id)arg1;
- (void)bandwidthSpeed:(long long)arg1;
- (void)dealloc;
- (void)addNotification;
- (id)init;
- (void)destroyInstance;
- (id)mutableCopy;
- (id)copy;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

