//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <netdisk-business/ALModel.h>

@class SpeedUpTrialPromptModel;

@interface SpeedUpTrialPromptContext : ALModel
{
    SpeedUpTrialPromptModel *_preTrialPrompt;
    SpeedUpTrialPromptModel *_onTrialPrompt;
    SpeedUpTrialPromptModel *_postTrialPompt;
    SpeedUpTrialPromptModel *_trayPrompt;
}

+ (id)modelContainerPropertyGenericClass;
+ (id)modelCustomPropertyMapper;
@property(retain, nonatomic) SpeedUpTrialPromptModel *trayPrompt; // @synthesize trayPrompt=_trayPrompt;
@property(retain, nonatomic) SpeedUpTrialPromptModel *postTrialPompt; // @synthesize postTrialPompt=_postTrialPompt;
@property(retain, nonatomic) SpeedUpTrialPromptModel *onTrialPrompt; // @synthesize onTrialPrompt=_onTrialPrompt;
@property(retain, nonatomic) SpeedUpTrialPromptModel *preTrialPrompt; // @synthesize preTrialPrompt=_preTrialPrompt;
- (void).cxx_destruct;

@end

