//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <netdisk-business/ALModel.h>

@class NSString;

@interface SpeedUpTrialPromptModel : ALModel
{
    NSString *_introduceDownTip;
    NSString *_introduceBackupTip;
    NSString *_introduceUpTip;
    NSString *_buttonEventDown;
    NSString *_buttnEventUp;
    NSString *_buttonMsgDown;
    NSString *_buttonMsgUp;
    NSString *_subIntroduceDownTip;
    NSString *_introDownNotGood;
    NSString *_traySubTip;
    NSString *_trayTitle;
}

+ (id)modelCustomPropertyMapper;
@property(copy, nonatomic) NSString *trayTitle; // @synthesize trayTitle=_trayTitle;
@property(copy, nonatomic) NSString *traySubTip; // @synthesize traySubTip=_traySubTip;
@property(copy, nonatomic) NSString *introDownNotGood; // @synthesize introDownNotGood=_introDownNotGood;
@property(copy, nonatomic) NSString *subIntroduceDownTip; // @synthesize subIntroduceDownTip=_subIntroduceDownTip;
@property(copy, nonatomic) NSString *buttonMsgUp; // @synthesize buttonMsgUp=_buttonMsgUp;
@property(copy, nonatomic) NSString *buttonMsgDown; // @synthesize buttonMsgDown=_buttonMsgDown;
@property(copy, nonatomic) NSString *buttnEventUp; // @synthesize buttnEventUp=_buttnEventUp;
@property(copy, nonatomic) NSString *buttonEventDown; // @synthesize buttonEventDown=_buttonEventDown;
@property(copy, nonatomic) NSString *introduceUpTip; // @synthesize introduceUpTip=_introduceUpTip;
@property(copy, nonatomic) NSString *introduceBackupTip; // @synthesize introduceBackupTip=_introduceBackupTip;
@property(copy, nonatomic) NSString *introduceDownTip; // @synthesize introduceDownTip=_introduceDownTip;
- (void).cxx_destruct;

@end

